


--June 9th – June 24th?


--IF NOT OBJECT_ID('tempdb..#invoices') IS NULL
--	DROP TABLE #invoices
--CREATE VIEW vNonMatchingInvoiceSalesOrder AS

WITH x AS (
	SELECT SOPNUMBE, ORIGNUMB, GLPOSTDT, DOCDATE
	--INTO #invoices
	FROM SOP30200
	WHERE SOPTYPE = 3 AND GLPOSTDT BETWEEN DATEADD(MM,-3,CAST(GETDATE() AS DATE)) AND CAST(GETDATE() AS DATE) AND BACKDATE = '1900-01-01 00:00:00.000'
)
SELECT TOP 100 PERCENT so.SOPNUMBE AS SONumber, inv.SOPNUMBE AS INVNumber, x.DOCDATE, x.GLPOSTDT, so.ITEMNMBR, so.ITEMDESC, so.QUANTITY AS SO_QTY, inv.QUANTITY AS INV_QTY, z.USER2ENT AS UserCreated
FROM SOP30300 inv
INNER JOIN x ON inv.SOPNUMBE = x.SOPNUMBE
INNER JOIN SOP30300 so ON x.ORIGNUMB = so.SOPNUMBE AND inv.ITEMNMBR = so.ITEMNMBR AND inv.UOFM = so.UOFM AND inv.LNITMSEQ = so.LNITMSEQ
OUTER APPLY (
				SELECT USER2ENT
				FROM SOP30200
				WHERE SOPNUMBE = so.SOPNUMBE
			) z
WHERE so.QUANTITY <> inv.QUANTITY  AND so.QTYPRBAC = 0
ORDER BY GLPOSTDT DESC, SONumber, ITEMNMBR
GO









SELECT *
FROM SOP30300
WHERE SOPNUMBE = 'SO00397131' AND ITEMNMBR = '113066'
SELECT *
FROM SOP30300
WHERE SOPNUMBE = 'STINV00314236' AND ITEMNMBR = '113066'


           
SELECT *
FROM SOP30200
WHERE SOPTYPE = 5



